"""
프로젝트 전역에서 사용하는 상태값/코드 문자열 상수.

DB 값, API JSON, 아두이노 메시지 모두 이 문자열을 기준으로 사용해야 함.
"""

# 주문 상태 (orders.status)
ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_COOKING = "COOKING"
ORDER_STATUS_DONE = "DONE"
ORDER_STATUS_PICKED_UP = "PICKED_UP"
ORDER_STATUS_CANCELED = "CANCELED"

# 머신 전체 상태 (machine_status.state)
MACHINE_STATE_IDLE = "IDLE"
MACHINE_STATE_RUNNING = "RUNNING"
MACHINE_STATE_ERROR = "ERROR"
MACHINE_STATE_EMERGENCY_STOP = "EMERGENCY_STOP"

# plate 상태 (plate1_state, plate2_state)
PLATE_STATE_IDLE = "IDLE"
PLATE_STATE_BAKING = "BAKING"
PLATE_STATE_DUMPING = "DUMPING"
PLATE_STATE_ERROR = "ERROR"

# 센서 상태
SENSOR_STATUS_OK = "OK"
SENSOR_STATUS_DISCONNECTED = "DISCONNECTED"
SENSOR_STATUS_OUT_OF_RANGE = "OUT_OF_RANGE"
SENSOR_STATUS_STUCK = "STUCK"

SIMPLE_SENSOR_OK = "OK"
SIMPLE_SENSOR_ERROR = "ERROR"
SIMPLE_SENSOR_STUCK = "STUCK"

# 재고 트랜잭션 타입 (material_tx.tx_type)
MATERIAL_TX_RESTOCK = "RESTOCK"
MATERIAL_TX_CONSUME = "CONSUME"
MATERIAL_TX_ADJUST = "ADJUST"

# 머신 이벤트 코드 (machine_event.event_code)
EVENT_ORDER_STARTED = "ORDER_STARTED"
EVENT_ORDER_DONE = "ORDER_DONE"
EVENT_PICKUP_DETECTED = "PICKUP_DETECTED"
EVENT_OVERHEAT = "OVERHEAT"
EVENT_EMERGENCY_STOP = "EMERGENCY_STOP"
EVENT_TEMP_SENSOR_FAIL = "TEMP_SENSOR_FAIL"
EVENT_TCRT_FAIL = "TCRT_FAIL"
EVENT_ULTRASONIC_FAIL = "ULTRASONIC_FAIL"
